Add Date Formatting to guidelines
freedomofpress/securedrop-docs pull request #107
Opened 2020-11-18 04:26 UTC by joaedwar

## Status

Ready for review 

## Description of Changes

* Description: Add formatting guidelines for dates in docs

* Fixes #50 

## Testing

*

## Release 

* 

## Checklist (Optional)

- [x] Doc linting (`make docs-lint`) passed locally
- [x] Doc link linting (`make docs-linkcheck`) passed
- [x] You have previewed (`make docs`) docs at http://localhost:8000

2020-11-18 04:27 UTC, joaedwar commented
@eloquence

2020-11-18 18:51 UTC, eloquence commented on LICENSE
> -                       Version 3, 19 November 2007
The license is a third party asset and should not be modified.

2020-11-18 18:55 UTC, eloquence requested changes
One requested change, otherwise LGTM :). Thanks @joaedwar

2020-11-25 19:58 UTC, joaedwar commented
@eloquence was this changed back?

2020-11-25 19:59 UTC, eloquence commented
@joaedwar What do you mean? I've not pushed to your branch, if that's what you're asking. The pending change (to restore the license to its original state) is still pending.

2020-11-30 23:08 UTC, eloquence approved these changes
I've reverted the LICENSE file change and updated your branch accordingly; this is now good to go, so merging.

2020-11-30 23:08 UTC, merged