Fix broken link to page of historical relevance (2)
freedomofpress/securedrop-docs pull request #127
Opened 2021-01-08 11:53 UTC by gonzalo-bulnes

## Status

Ready for review

## Description of Changes

This PR is a follow up on #118. I misspelled the timestamp in the link :disappointed: 

Fixes #126 

## Testing

- [ ] This time, when running `make docs-linkcheck` the logs should report `ok` instead of `redirect / found`.
```
(line   86) ok        https://web.archive.org/web/20201114214553/https://specialprojectsdesk.com/tell-on-trump-1792401813
```

## Release 

I can't think of any special consideration before releasing this change.

## Checklist (Optional)

- [x] Doc linting (`make docs-lint`) passed locally
- [x] Doc link linting (`make docs-linkcheck`) passed  (not only passed but doesn't report the tell-tale redirect)
- [ ] You have previewed (`make docs`) docs at http://localhost:8000

2021-01-08 17:08 UTC, zenmonkeykstop requested changes

2021-01-08 17:08 UTC, zenmonkeykstop commented on docs/getting_the_most_out_of_securedrop.rst
> +.. _`tell on trump`: https://web.archive.org/web/20201114214553/https://specialprojectsdesk.com/tell-on-trump-1792401813
This returns a 200 from the IA, but the recorded page is a Kinja 404. Using an earlier version like https://web.archive.org/web/20200926063152/https://specialprojectsdesk.com/tell-on-trump-1792401813 works.

2021-01-08 22:46 UTC, gonzalo-bulnes commented on docs/getting_the_most_out_of_securedrop.rst
> +.. _`tell on trump`: https://web.archive.org/web/20201114214553/https://specialprojectsdesk.com/tell-on-trump-1792401813
I picked the last date that didn't display the Kinja 404 page, so the green/corrected link shouldn't  do that (Nov. 14) - though the [misspelled URL sometimes did](https://github.com/freedomofpress/securedrop-docs/issues/126). **That being said**, the September 26 version is just as fine. I'll make the change :+1:

2021-01-13 08:52 UTC, gonzalo-bulnes commented
(rebased)

2021-01-13 17:57 UTC, eloquence approved these changes
LGTM and `make docs-linkcheck` succeeds now, thanks for the Internet Archive trial & error.

2021-01-13 17:57 UTC, merged