Add note about develop branch
freedomofpress/securedrop-docs pull request #15
Opened 2020-10-01 20:16 UTC by joaedwar

Pull requests should be opened against the `main` branch. For more information on contributing to SecureDrop documentation, see the [Documentation Guidelines](https://docs.securedrop.org/en/stable/development/documentation_guidelines.html).

## Status
*(What state is your PR in? Select one of the following and delete the option that does not apply.)*

Ready for review 

## Description of Changes

* Description: 

* Fixes [Issue#4951](https://github.com/freedomofpress/securedrop/issues/4951)

## Testing
*(How should the reviewer test this PR? Write out any special testing steps here.)*
* n/a

## Release 
*(Any special considerations for release of this change into the stable version of the documentation?)*
* n/a

## Checklist (Optional)

- [ ] Doc linting (`make docs-lint`) passed locally
- [ ] Doc link linting (`make docs-linkcheck`) passed
- [x] You have previewed (`make docs`) docs at http://localhost:8000

2020-10-01 20:19 UTC, eloquence requested changes

2020-10-01 20:19 UTC, eloquence commented on docs/development/setup_development.rst
> +   changes should be pushed to the ``develop`` git branch of our repository_.
Technically, we don't want contributors to push to `develop` directly, but to open PRs, which are then merged by a maintainer.

I would simplify: 

> PRs should be opened against the ``develop`` branch of our repository, which is the primary branch used for development.

Or something to that effect.

2020-10-05 15:44 UTC, zenmonkeykstop approved these changes
LGTM based on visual review.

2020-10-05 19:28 UTC, closed without merging

2020-10-05 19:36 UTC, eloquence commented
This PR was accidentally closed as part of a force push, and GitHub now no longer lets me push to the remote -- but that's probably for the best, as it's opened from the `main` branch of your fork. I've reopened as #20.