adds summary table of staging versus production virtual environments
freedomofpress/securedrop-docs pull request #280
Opened 2021-11-25 00:36 UTC by cfm

## Status

Ready for review

## Description of Changes

In cfm/terraform-metal-securedrop-staging#3, I realized I'd gotten a bit confused between the staging- and production-grade [virtual environments](https://docs.securedrop.org/en/stable/development/virtual_environments.html) on account of how I was both using and tooling for them during the SecureDrop 2.1.0 QA cycle.  The change proposed here puts a summary table at the top of the "Virtual Environments" page to compare them so that their differences and possible uses are more readily apparent.

## Testing

Is the table correct?  Does it seem useful to you? clear?

## Release 

Relevant only during development and QA; no release considerations.

## Checklist (Optional)

- [x] Doc linting (`make docs-lint`) passed locally
- [ ] Doc link linting (`make docs-linkcheck`) passed
    * No; will fix separately.
- [x] You have previewed (`make docs`) docs at http://localhost:8000

2021-11-25 16:09 UTC, zenmonkeykstop requested changes
I think the difference between prod and staging virtual environments could definitely do with being clarified up front, rather than in their individual sections in this doc, to help devs choose the right environment for their needs more quickly, but I dont think the table works very well for that.
There's also some over-simplifications as mentioned in comments that would probably lead to more work, not less, for devs.

It might be worth looking at moving the initial descriptions in the staging and prod sections of this doc up to the main section instead?

2021-11-25 16:09 UTC, zenmonkeykstop commented on docs/development/virtual_environments.rst
> +| :ref:`Production environment <production_vms>` | Tails-level ``securedrop-admin {sdconfig,install}`` | ``apt.freedom.press``          | via ``securedrop-admin tailsconfig``   |
Similarly, the prod VM environment doesn't have to use `apt.freedom.press` - frequently in practice (at least during QA) you might use `apt-test.freedom.press` instead, or if testing upgrades (eg. for postint behavior) a temporarily-created apt server.

2022-01-21 00:03 UTC, cfm commented on docs/development/virtual_environments.rst
> +| :ref:`Staging environment <staging_vms>`       | host-level ``make staging``                         | host-level ``make build-debs`` | manually                               |
Hmm.  `make staging` without `make build-debs` gives me:

<details>
<summary>
<code>Jan 20 23:40:16 localhost cloud-init[1157]:     TASK [Fail if package is missing
 from build dir] *******************************</code>
</summary>

```
Jan 20 23:40:16 localhost cloud-init[1157]:     TASK [Fail if package is missing from build dir] *******************************
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=securedrop-keyring-0.1.5+2.2.0~rc1+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "securedrop-keyring-0.1.5+2.2.0~rc1+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/securedrop-keyring-0.1.5+2.2.0~rc1+focal-amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=securedrop-config-0.1.4+2.2.0~rc1+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "securedrop-config-0.1.4+2.2.0~rc1+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/securedrop-config-0.1.4+2.2.0~rc1+focal-amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=securedrop-ossec-agent-3.6.0+2.2.0~rc1+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "securedrop-ossec-agent-3.6.0+2.2.0~rc1+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/securedrop-ossec-agent-3.6.0+2.2.0~rc1+focal-amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=securedrop-grsec-5.4.136+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "securedrop-grsec-5.4.136+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/securedrop-grsec-5.4.136+focal-amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=securedrop-app-code_2.2.0~rc1+focal_amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "securedrop-app-code_2.2.0~rc1+focal_amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/securedrop-app-code_2.2.0~rc1+focal_amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=ossec-agent-3.6.0+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "ossec-agent-3.6.0+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/ossec-agent-3.6.0+focal-amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=securedrop-keyring-0.1.5+2.2.0~rc1+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "securedrop-keyring-0.1.5+2.2.0~rc1+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/securedrop-keyring-0.1.5+2.2.0~rc1+focal-amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=securedrop-config-0.1.4+2.2.0~rc1+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "securedrop-config-0.1.4+2.2.0~rc1+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/securedrop-config-0.1.4+2.2.0~rc1+focal-amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=securedrop-ossec-server-3.6.0+2.2.0~rc1+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "securedrop-ossec-server-3.6.0+2.2.0~rc1+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/securedrop-ossec-server-3.6.0+2.2.0~rc1+focal-amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=securedrop-grsec-5.4.136+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "securedrop-grsec-5.4.136+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/securedrop-grsec-5.4.136+focal-amd64.deb missing"}
Jan 20 23:40:16 localhost cloud-init[1157]:     failed: [localhost] (item=ossec-server-3.6.0+focal-amd64.deb) => {"ansible_loop_var": "item", "changed": false, "item": "ossec-server-3.6.0+focal-amd64.deb", "msg": "run 'make build-debs' - ../../build/focal/ossec-server-3.6.0+focal-amd64.deb missing"}
```
</details>

From your comment, it sounds like this is not the expected behavior?

(Testing in the context of cfm/terraform-metal-securedrop-staging#5 and filing here before I forget.)

2022-03-31 06:24 UTC, cfm commented
Yep, just haven't gotten back to `cfm/terraform-metal-securedrop-staging` as the motivation and context for this addition.  If that's a bother, feel free to close this pull request as is, and I'll reopen it once I've been able to revisit it.

2023-05-09 18:09 UTC, cfm commented
Closing this as obsoleted by #387; I'm unlikely to pick it back up in the new `securedrop-dev-docs`.

2023-05-09 18:09 UTC, closed without merging