Update set_up_svs.rst
freedomofpress/securedrop-docs pull request #427
Opened 2023-02-15 13:58 UTC by KwadroNaut

Fixes updated time settings menu

## Status
Work in progress. Need to add a screenshot.

## Description of Changes

* Tails got some updates, how you got to the settings in the gui has changed.

* Resolves #
https://github.com/freedomofpress/dangerzone/issues/342

## Checklist (Optional)

- [ ] Doc linting (`make docs-lint`) passed locally
- [ ] Doc link linting (`make docs-linkcheck`) passed
- [ ] You have previewed (`make docs`) docs at http://localhost:8000

2023-02-15 14:02 UTC, KwadroNaut commented
Ready for review.

2023-03-01 18:09 UTC, nathandyer requested changes
Thanks @KwadroNaut! I suggested a minor change to one line, but otherwise, it looks good to me. As always, thanks for the PR!

2023-03-01 18:09 UTC, nathandyer commented on docs/set_up_svs.rst
> +#. Click in the top left menu Applications, go to **System Tools** and select Settings
The buttons/targets that users will click should be bolded so they stand out as UI elements in the instructions. There are also some flow issues with the first part of the line. I might suggest a slightly tweaked version like this:

```
#. Click **Applications** in the top left of the screen, then go to **System Tools** and select **Settings**/
```

2023-06-02 23:59 UTC, eloquence commented
@KwadroNaut Would you like us to pick this one up to get it over the line?

2024-09-25 21:45 UTC, nathandyer commented
This PR has been superseded by others since it was originally filed; closing as the original issue is resolved.

2024-09-25 21:45 UTC, closed without merging