Update release management guidelines
freedomofpress/securedrop-docs pull request #8
Opened 2020-09-24 22:57 UTC by eloquence

This fleshes out the guide for collaborating with the Communications Manager on a release, including the preparatory steps of creating a docs PR with release-specific upgrade instructions. 

It describes the tooling changes introduced in https://github.com/freedomofpress/securedrop/pull/5520, so we should wait until those have been sanity-checked before merging.

It also encapsulates the one trade-off with our current branching/tagging strategy: in some cases, we may have to create a release-specific branch to ensure we don't pick up documentation changes in `main` that are not yet releasable. This is likely to be rare, but it can happen.

2020-09-25 00:36 UTC, conorsch commented
First pass looks pretty darn good. Had some trouble verifying this step:

> bumps the SecureDrop version of the documentation using the `update_version.sh` script in that repository

but that's attributable to https://github.com/freedomofpress/securedrop/issues/5530, not a flaw in the docs here. Still, will want to verify that functionality prior to finalizing review.

2020-09-29 01:16 UTC, eloquence commented
Marking as ready now that https://github.com/freedomofpress/securedrop/pull/5520 is merged.

2020-09-29 15:03 UTC, zenmonkeykstop approved these changes
LGTM with one teeny nit

2020-09-29 15:03 UTC, zenmonkeykstop commented on docs/development/release_management.rst
> +    and so on,
nit: comma instead of a period.

2020-09-29 15:03 UTC, zenmonkeykstop requested changes
LGTM with one teeny nit

2020-09-29 17:20 UTC, eloquence commented on docs/development/release_management.rst
> +    and so on,
Fixed

2020-09-29 17:20 UTC, eloquence commented
(Squashed into one commit)

2020-09-29 17:23 UTC, zenmonkeykstop approved these changes
LGTM, approving

2020-09-29 17:23 UTC, merged