Update Docs guidelines
freedomofpress/securedrop-docs pull request #9
Opened 2020-09-29 11:22 UTC by joaedwar

Updates docs guidelines to reflect using new dedicated docs repo. 

Refers to [Issue#4](https://github.com/freedomofpress/securedrop-docs/issues/4)

2020-09-29 17:38 UTC, eloquence commented on docs/development/documentation_guidelines.rst
> +automatically when commits get pushed to the branch.
Moving the paragraph that starts with "Our documentation .." makes it obvious how duplicative it is -- compare it with the first paragraph in this chapter:

> SecureDrop’s documentation is written in ReStructuredText (ReST), and is built by and hosted on Read the Docs (RTD). The documentation files are stored in the primary SecureDrop git repository under the docs/ directory.

I would suggest consolidating these two paragraphs in the introductory paragraph. The use of a webhook is a technical detail that I would be happy to remove.

2020-09-29 17:43 UTC, eloquence commented on docs/development/documentation_guidelines.rst
> +   You can then preview the documentation at http://127.0.0.1:8000. The documentation pages will automatically rebuild in the browser
I'm very open to revisiting this, but our current documentation guidelines (further in this chapter) suggest limiting the length of a line to about 80 characters unless long URLs or code blocks push it over the limit, so for now I would suggest applying the same line length throughout your changes.

2020-09-29 17:44 UTC, eloquence commented on docs/development/documentation_guidelines.rst
>  The :ref:`CI tests<ci_tests>` by default create staging servers to test the
You can also remove this sentence, as these tests no longer run in the `securedrop-docs` repo.

2020-09-29 17:47 UTC, eloquence commented on docs/development/documentation_guidelines.rst
> +A quick reference on writting in `ReStructuredText`_ (ReST)
I would suggest to make this a full sentence, e.g., "Please see the reStructuredText Primer[link] by the Sphinx project for an introduction to the markup language used for the documentation." or similar Also typo: `writting`

2020-09-29 17:48 UTC, eloquence requested changes
Thanks much for preparing, requested a few small changes inline.

2020-09-29 17:53 UTC, conorsch commented
Heads up, rebase required to resolve conflicts introduced from merge of https://github.com/freedomofpress/securedrop-docs/pull/8

2020-09-29 23:05 UTC, eloquence commented
(Joan is working on cleanly rebasing this PR and making some final tweaks.)

2020-09-30 17:00 UTC, conorsch commented
@eloquence Pointed out that the CI was stuck in "waiting" state on this PR. The problem was that CircleCI did not have the "build from forked PRs" option enabled, as we have in the "securedrop" repo for example. I've enabled it now. It'll take another force-push to kick CI again, at which point it should run to completion!

2020-09-30 18:05 UTC, eloquence approved these changes

2020-09-30 18:06 UTC, eloquence commented
LGTM, thanks much for preparing @joaedwar!

2020-09-30 18:06 UTC, merged